source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'BiometryExample' do
    use_frameworks!
    pod 'BiometryAuthUI', :git => 'https://github.com/AntonBelousov/BiometryAuthUI.git'
end
